services:
  frontend:
    build:
      context: ./nextjs-app
    container_name: nextjs-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - ./public:/nextjs-app/public

  backend:
    build:
      context: ./backend
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    networks:
      - app-network
    volumes:
      - ./public:/nextjs-app/public

networks:
  app-network:
    driver: bridge
